/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.rezervacija;

import domain.Soba;
import form.klijent.DodajKlijentaForm;
import form.soba.DodajSobuForm;
import form.usluga.DodajUsluguForm;
import form.zaposleni.DodajZaposlenogForm;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Boris
 */
public class KreiranjeRezervacijeForm extends javax.swing.JFrame{

    /**
     * Creates new form FormKreiranjeRezervacije
     */
    public KreiranjeRezervacijeForm() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDatumOd = new javax.swing.JFormattedTextField();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIzaberiKlijenta = new javax.swing.JButton();
        lblKlijentIzabrani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSobe = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIzabraneSobe = new javax.swing.JTable();
        txtPretragaSoba = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIzaberiSobu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPretragaUsluga = new javax.swing.JTextField();
        btnIzaberiUslugu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsluge = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIzabraneUsluge = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblTrenutnoUlogovaniKorisnik = new javax.swing.JLabel();
        lblSat = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnIzvrsirezervaciju = new javax.swing.JButton();
        btnIzbrisiIzabranuSobu = new javax.swing.JButton();
        btnIzbrisiIzabranuUslugu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtBrojKoriscenjaUsluge = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKlijenti = new javax.swing.JMenu();
        menuItemNoviKlijent = new javax.swing.JMenuItem();
        menuItemPretragaKlijenta = new javax.swing.JMenuItem();
        menuZaposleni = new javax.swing.JMenu();
        menuItemNoviZaposleni = new javax.swing.JMenuItem();
        menuItemPretragaZaposleni = new javax.swing.JMenuItem();
        menuRezervacije = new javax.swing.JMenu();
        menuItemPretragaRezervacija = new javax.swing.JMenuItem();
        menuSobe = new javax.swing.JMenu();
        menuItemNovaSoba = new javax.swing.JMenuItem();
        menuItemPretragaSoba = new javax.swing.JMenuItem();
        menuItemNoviTipSobe = new javax.swing.JMenuItem();
        menuUsluge = new javax.swing.JMenu();
        menuItemNovaUsluga = new javax.swing.JMenuItem();
        menuItemPretragaUsluga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KREIRANJE REZERVACIJE");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumOd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumOdKeyReleased(evt);
            }
        });

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumDo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumDoKeyReleased(evt);
            }
        });

        jLabel1.setText("Datum od:");

        jLabel2.setText("Datum do:");

        btnIzaberiKlijenta.setText("Izaberi klijenta");

        lblKlijentIzabrani.setText("Klijent nije izabran");

        tblSobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSobe);

        tblIzabraneSobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIzabraneSobe);

        txtPretragaSoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaSobaKeyReleased(evt);
            }
        });

        jLabel3.setText("Pretraga sobe");

        btnIzaberiSobu.setText("Izaberi sobu");
        btnIzaberiSobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiSobuActionPerformed(evt);
            }
        });

        jLabel4.setText("Izabrane sobe:");

        jLabel5.setText("Pretraga usluga");

        btnIzaberiUslugu.setText("Izaberi uslugu");

        tblUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblUsluge);

        tblIzabraneUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblIzabraneUsluge);

        jLabel6.setText("Izabrane usluge:");

        lblTrenutnoUlogovaniKorisnik.setText("Trenutno ulogovani zaposleni");

        lblSat.setText("Sat");

        btnCancel.setText("Odustani");

        btnIzvrsirezervaciju.setText("Izvrši rezervaciju");
        btnIzvrsirezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzvrsirezervacijuActionPerformed(evt);
            }
        });

        btnIzbrisiIzabranuSobu.setText("Izbriši izabranu sobu");
        btnIzbrisiIzabranuSobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiIzabranuSobuActionPerformed(evt);
            }
        });

        btnIzbrisiIzabranuUslugu.setText("Izbriši izabranu uslugu");

        jLabel8.setText("Broj dana korišćenja:");

        menuKlijenti.setText("Klijenti");

        menuItemNoviKlijent.setText("Novi klijent");
        menuItemNoviKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviKlijentActionPerformed(evt);
            }
        });
        menuKlijenti.add(menuItemNoviKlijent);

        menuItemPretragaKlijenta.setText("Pretraga klijenata");
        menuKlijenti.add(menuItemPretragaKlijenta);

        jMenuBar1.add(menuKlijenti);

        menuZaposleni.setText("Zaposleni");

        menuItemNoviZaposleni.setText("Novi zaposleni");
        menuItemNoviZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviZaposleniActionPerformed(evt);
            }
        });
        menuZaposleni.add(menuItemNoviZaposleni);

        menuItemPretragaZaposleni.setText("Pretraga zaposlenih");
        menuZaposleni.add(menuItemPretragaZaposleni);

        jMenuBar1.add(menuZaposleni);

        menuRezervacije.setText("Rezervacije");

        menuItemPretragaRezervacija.setText("Pretraga rezervacija");
        menuRezervacije.add(menuItemPretragaRezervacija);

        jMenuBar1.add(menuRezervacije);

        menuSobe.setText("Sobe");

        menuItemNovaSoba.setText("Nova soba");
        menuItemNovaSoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaSobaActionPerformed(evt);
            }
        });
        menuSobe.add(menuItemNovaSoba);

        menuItemPretragaSoba.setText("Pretraga soba");
        menuSobe.add(menuItemPretragaSoba);

        menuItemNoviTipSobe.setText("Novi tip sobe");
        menuItemNoviTipSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviTipSobeActionPerformed(evt);
            }
        });
        menuSobe.add(menuItemNoviTipSobe);

        jMenuBar1.add(menuSobe);

        menuUsluge.setText("Usluge");

        menuItemNovaUsluga.setText("Nova usluga");
        menuItemNovaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaUslugaActionPerformed(evt);
            }
        });
        menuUsluge.add(menuItemNovaUsluga);

        menuItemPretragaUsluga.setText("Pretraga usluga");
        menuUsluge.add(menuItemPretragaUsluga);

        jMenuBar1.add(menuUsluge);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzvrsirezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPretragaSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzaberiSobu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIzbrisiIzabranuSobu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzaberiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                    .addComponent(txtDatumDo))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPretragaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrenutnoUlogovaniKorisnik)
                                    .addComponent(lblSat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtBrojKoriscenjaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addComponent(btnIzaberiUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnIzbrisiIzabranuUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKlijentIzabrani, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblTrenutnoUlogovaniKorisnik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblSat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzaberiKlijenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKlijentIzabrani, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPretragaSoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzaberiSobu)
                    .addComponent(jLabel5)
                    .addComponent(txtPretragaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(btnIzbrisiIzabranuSobu)
                            .addComponent(btnIzbrisiIzabranuUslugu)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txtBrojKoriscenjaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(btnIzaberiUslugu)
                            .addGap(23, 23, 23))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzvrsirezervaciju)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNoviKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviKlijentActionPerformed
        
    }//GEN-LAST:event_menuItemNoviKlijentActionPerformed

    private void menuItemNoviZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviZaposleniActionPerformed
        
    }//GEN-LAST:event_menuItemNoviZaposleniActionPerformed

    private void menuItemNovaSobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovaSobaActionPerformed
        
    }//GEN-LAST:event_menuItemNovaSobaActionPerformed

    private void menuItemNovaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovaUslugaActionPerformed
        
    }//GEN-LAST:event_menuItemNovaUslugaActionPerformed

    private void txtDatumOdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumOdKeyReleased
        
    }//GEN-LAST:event_txtDatumOdKeyReleased

    private void txtDatumDoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumDoKeyReleased
        
    }//GEN-LAST:event_txtDatumDoKeyReleased

    private void txtPretragaSobaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaSobaKeyReleased
        
    }//GEN-LAST:event_txtPretragaSobaKeyReleased

    private void btnIzaberiSobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiSobuActionPerformed
        
    }//GEN-LAST:event_btnIzaberiSobuActionPerformed

    private void btnIzbrisiIzabranuSobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiIzabranuSobuActionPerformed
        
    }//GEN-LAST:event_btnIzbrisiIzabranuSobuActionPerformed

    private void menuItemNoviTipSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviTipSobeActionPerformed
        
    }//GEN-LAST:event_menuItemNoviTipSobeActionPerformed

    private void btnIzvrsirezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzvrsirezervacijuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzvrsirezervacijuActionPerformed

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnIzaberiKlijenta;
    private javax.swing.JButton btnIzaberiSobu;
    private javax.swing.JButton btnIzaberiUslugu;
    private javax.swing.JButton btnIzbrisiIzabranuSobu;
    private javax.swing.JButton btnIzbrisiIzabranuUslugu;
    private javax.swing.JButton btnIzvrsirezervaciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblKlijentIzabrani;
    private javax.swing.JLabel lblSat;
    private javax.swing.JLabel lblTrenutnoUlogovaniKorisnik;
    private javax.swing.JMenuItem menuItemNovaSoba;
    private javax.swing.JMenuItem menuItemNovaUsluga;
    private javax.swing.JMenuItem menuItemNoviKlijent;
    private javax.swing.JMenuItem menuItemNoviTipSobe;
    private javax.swing.JMenuItem menuItemNoviZaposleni;
    private javax.swing.JMenuItem menuItemPretragaKlijenta;
    private javax.swing.JMenuItem menuItemPretragaRezervacija;
    private javax.swing.JMenuItem menuItemPretragaSoba;
    private javax.swing.JMenuItem menuItemPretragaUsluga;
    private javax.swing.JMenuItem menuItemPretragaZaposleni;
    private javax.swing.JMenu menuKlijenti;
    private javax.swing.JMenu menuRezervacije;
    private javax.swing.JMenu menuSobe;
    private javax.swing.JMenu menuUsluge;
    private javax.swing.JMenu menuZaposleni;
    private javax.swing.JTable tblIzabraneSobe;
    private javax.swing.JTable tblIzabraneUsluge;
    private javax.swing.JTable tblSobe;
    private javax.swing.JTable tblUsluge;
    private javax.swing.JTextField txtBrojKoriscenjaUsluge;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextField txtPretragaSoba;
    private javax.swing.JTextField txtPretragaUsluga;
    // End of variables declaration//GEN-END:variables

    

    public JTable getTblIzabraneSobe() {
        return tblIzabraneSobe;
    }

    public JTable getTblIzabraneUsluge() {
        return tblIzabraneUsluge;
    }

    public JTable getTblSobe() {
        return tblSobe;
    }

    public JTable getTblUsluge() {
        return tblUsluge;
    }

    public JFormattedTextField getTxtDatumDo() {
        return txtDatumDo;
    }

    public JFormattedTextField getTxtDatumOd() {
        return txtDatumOd;
    }

    public JTextField getTxtPretragaSoba() {
        return txtPretragaSoba;
    }

    public JTextField getTxtPretragaUsluga() {
        return txtPretragaUsluga;
    }

    
    public JRootPane getRootPane() {
        return rootPane;
    }

    public JLabel getLblKlijentIzabrani() {
        return lblKlijentIzabrani;
    }

    public JLabel getLblSat() {
        return lblSat;
    }

    public JLabel getLblTrenutnoUlogovaniKorisnik() {
        return lblTrenutnoUlogovaniKorisnik;
    }

    public JMenuItem getMenuItemNovaSoba() {
        return menuItemNovaSoba;
    }

    public JMenuItem getMenuItemNovaUsluga() {
        return menuItemNovaUsluga;
    }

    public JMenuItem getMenuItemNoviKlijent() {
        return menuItemNoviKlijent;
    }

    public JMenuItem getMenuItemNoviTipSobe() {
        return menuItemNoviTipSobe;
    }

    public JMenuItem getMenuItemNoviZaposleni() {
        return menuItemNoviZaposleni;
    }

    public JMenuItem getMenuItemPretragaKlijenta() {
        return menuItemPretragaKlijenta;
    }

    public JMenuItem getMenuItemPretragaRezervacija() {
        return menuItemPretragaRezervacija;
    }

    public JMenuItem getMenuItemPretragaSoba() {
        return menuItemPretragaSoba;
    }

    public JMenuItem getMenuItemPretragaUsluga() {
        return menuItemPretragaUsluga;
    }

    public JMenuItem getMenuItemPretragaZaposleni() {
        return menuItemPretragaZaposleni;
    }

    public JMenu getMenuKlijenti() {
        return menuKlijenti;
    }

    public JMenu getMenuRezervacije() {
        return menuRezervacije;
    }

    public JMenu getMenuSobe() {
        return menuSobe;
    }

    public JMenu getMenuUsluge() {
        return menuUsluge;
    }

    public JMenu getMenuZaposleni() {
        return menuZaposleni;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnIzaberiKlijenta() {
        return btnIzaberiKlijenta;
    }

    public JButton getBtnIzaberiSobu() {
        return btnIzaberiSobu;
    }

    public JButton getBtnIzaberiUslugu() {
        return btnIzaberiUslugu;
    }

    public JButton getBtnIzbrisiIzabranuSobu() {
        return btnIzbrisiIzabranuSobu;
    }

    public JButton getBtnIzbrisiIzabranuUslugu() {
        return btnIzbrisiIzabranuUslugu;
    }
    
    public JButton getBtnIzvrsirezervaciju() {
        return btnIzvrsirezervaciju;
    }

    public JTextField getTxtBrojKoriscenjaUsluge() {
        return txtBrojKoriscenjaUsluge;
    }
    
    
}
